apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <CHART_NAME>-tls
  namespace: <K8S_NAMESPACE>
spec:
  secretName: <CHART_NAME>-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: <HOST_ADDR>
  dnsNames:
    - <HOST_ADDR>
